version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-lambda-stack"
s3_bucket = "xxxxxxxxxxxxxxxx"
s3_prefix = "my-lambda-stack"
region = "us-east-1"
capabilities = ["CAPABILITY_NAMED_IAM", "CAPABILITY_IAM"]
confirm_changeset = true
fail_on_empty_changeset = false
image_repositories = []